# Aider Configuration - Configuração baseada no README.md
# Este arquivo define as regras e configurações para o Aider no ambiente AGC

# 1. Visão geral e definições (conforme README.md)
visão_geral:
  objetivo: "Manter a consistência entre Codex, Gemini, Cline e Aider"
  definição_agc:
    - "Agents.md (Codex)"
    - "Gemini.md (Contexto do Gemini)"
    - "Cline rules (.clinerules)"
    - "Aider conventions (.aider.conf.yml / conventions.md)"
  suporte_adicional:
    - "Agent Skills nativas (Codex)"
    - "Cline como agente autônomo com suporte avançado a MCP"

# 2. Instruções personalizadas de estilo (conforme README.md)
estilo_escrita:
  - "Escreva de forma fluida e articulada, conectando ideias logicamente, mas utilize um registro de linguagem natural e acessível, evitando estritamente o academicismo excessivo, jargões complexos ou orações labirínticas que prejudiquem a leitura"
  - "Busque um equilíbrio rítmico: combine frases articuladas com pausas claras e vocabulário cotidiano, garantindo que a sofisticação esteja na clareza do raciocínio e não na dificuldade das palavras, tornando o texto envolvente sem ser denso ou cansativo"
  - "Evite estruturas de frase que criem uma expectativa para depois negá-la ou expandi-la. Em vez disso, use afirmações diretas e positivas"
  - "Sinta-se à vontade para ser criativo na construção das frases e nos estilos de expressão"

formatação:
  - "Não use maiúscula para fins estilísticos, use sentence case sempre que possível"
  - "Não use emojis"
  - "Não use em dashes, travessões ou hífens no lugar de vírgula"

# 3. Perfil do usuário (conforme README.md)
perfil_usuário:
  nome: "Lucas Camilo Carvalho"
  localização: "Salvador, Bahia"
  idiomas:
    - "Português (Primário)"
    - "Inglês (Secundário)"

# 4. Configurações do ambiente (conforme README.md)
ambiente:
  sistema_operacional: "Lubuntu"
  caminho_base_gdrive: "/run/user/1000/gvfs/dav:host=app.koofr.net,ssl=true,user=lucascamr107%40gmail.com,prefix=%2Fdav/Google Drive/"
  diretório_gemini_gems: "Gemini Gems/"

# 5. Protocolos de leitura e execução (conforme README.md)
protocolos:
  leitura_gems:
    comando: 'cat "Nome do Arquivo.gem"'
    observação: "Use sempre aspas duplas para caminhos com espaços. Arquivos podem iniciar com emojis (ex.: ❗)"
  criação_gems:
    padrão_nome: "❗ Estrutura {Nome do prompt}"
    extensões: [".txt", ".json", ".md"]
    observação: "Crie arquivos com extensões explícitas para conteúdo legível"

# 6. Hierarquia de configuração (conforme README.md)
hierarquia_configuração:
  - "System Defaults (system-defaults.json)"
  - "User Settings (~/.gemini/settings.json)"
  - "Workspace Settings (<projeto>/.gemini/settings.json)"
  - "System Overrides (settings.json)"

# 7. Locais de configuração AGC (conforme README.md)
locais_agc:
  codex: "~/.codex/AGENTS.md"
  cline: ".clinerules"
  gemini: "System Instructions (via configurações do usuário ou Gems)"
  aider: "~/.aider.conf.yml"

# 8. Instruções para MCP (conforme README.md)
mcp:
  slack:
    comando: "npx"
    args: ["-y", "@modelcontextprotocol/server-slack"]
    env:
      SLACK_BOT_TOKEN: "xoxb-seu-token"
      SLACK_TEAM_ID: "T01234567"
  filesystem:
    comando: "npx"
    args: ["-y", "@modelcontextprotocol/server-filesystem", "/home/lucas"]

# 9. Instruções para Skills (conforme README.md)
skills:
  codex:
    local_padrão: "~/.codex/skills"
    estrutura:
      pasta: true
      arquivo_obrigatório: "SKILL.md"
      frontmatter:
        - name
        - description
        - metadata.short-description
    invocação:
      explícita: "/skills ou $"
      implícita: "Codex decide com base na descrição"
    instalação:
      comando: "$skill-installer <nome-da-skill>"
      exemplo: "$skill-installer linear"
    criação:
      automática: "$skill-creator"
      manual: "Crie pasta com SKILL.md contendo frontmatter YAML"
  aider:
    nota: "O Aider não suporta o padrão de Agent Skills do Codex. Descreva capacidades específicas neste arquivo ou crie ferramentas MCP via linguagem natural"

# 10. Instruções para Prompts (conforme README.md)
prompts:
  codex:
    local: "~/.codex/prompts/"
    formato: "Markdown com frontmatter YAML"
    invocação: "/prompts:nome-do-arquivo"

# 11. Variáveis de ambiente sugeridas (conforme README.md)
variáveis_ambiente:
  GDRIVE: "/run/user/1000/gvfs/dav:host=app.koofr.net,ssl=true,user=lucascamr107%40gmail.com,prefix=%2Fdav/Google Drive/"

# 12. Comandos úteis (conforme README.md)
comandos:
  verificação_codex: 'codex --ask-for-approval never "Show which instruction files are active."'
  instalação_extensões_gemini: "gemini extensions install <url-do-repositorio>"
  instalação_skills_codex: "$skill-installer <nome-da-skill>"
  criação_skills_codex: "$skill-creator"
  verificação_mcp: "/mcp"

# 13. Configurações específicas do Aider (conforme README.md)
aider:
  read:
    - "~/Documents/AGCA_Master.md"
  conventions:
    - "Use sempre o formato YAML para configurações"
    - "Mantenha a consistência com os outros arquivos AGCA"
    - "Atualize este arquivo sempre que o README.md for modificado"
